// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ConAppDiamondML.Model
{
    public class ModelInput
    {
        [ColumnName("Carot"), LoadColumn(0)]
        public float Carot { get; set; }


        [ColumnName("Price"), LoadColumn(1)]
        public float Price { get; set; }


    }
}
